### ISSUE TITLE
Timed Out quand on éxécute une commande après le login

### ISSUE THREAD

**Issue by OVERgamingTube** [DeadCube/MinewebAuthPlugin#1]
Salut, après le login le plugin me timed out et affiche une tonne d'erreurs dans la console.

Aussi, il faudrait ajouter un support FastLogin pour permettre de /premium les joueurs qui sont premium.

Cordialement et merci d'avance.

**Comment by DeadCube** [comment]
@OVERgamingTube 
Le site renseigné dans la `config.yml` est mauvais.
De plus, l'API marche quand le site n'est pas en maintenance

Le premium pourra est une bonne idée :).
Pour l'instant, je ne veux pas croiser le plugin avec d'autres...

**Comment by OVERgamingTube** [comment]
Ok, ça marche ! Merci de ton aide ^^

Bonne journée/soirée à toi !
